permalink: /:title/

kramdown:
  auto_ids: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

nav:
  en:
    journal:
      title: "journal"
      url:   "/index.html"
    about:
      title: "about"
      url:   "/about/"
  fr:
    journal:
      title: "journal"
      url:   "/journal/"
    about:
      title: "Ã  propos"
      url:   "/a-propos/"

cat:
  jekyll: "Jekyll"
  pi:     "Raspberry Pi"
  r:      "R"